/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsSlugRouteImport } from './routes/tournaments.$slug'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as AuthenticatedWithdrawalsRouteImport } from './routes/_authenticated/withdrawals'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDisputesRouteImport } from './routes/_authenticated/disputes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTeamsCreateRouteImport } from './routes/_authenticated/teams.create'
import { Route as AuthenticatedMatchesIdRouteImport } from './routes/_authenticated/matches.$id'
import { Route as AuthenticatedAdminTournamentsRouteImport } from './routes/_authenticated/admin/tournaments'
import { Route as AuthenticatedAdminOperationsRouteImport } from './routes/_authenticated/admin/operations'
import { Route as AuthenticatedAdminMatchesRouteImport } from './routes/_authenticated/admin/matches'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin/finance'
import { Route as AuthenticatedAdminDisputesIdRouteImport } from './routes/_authenticated/admin/disputes.$id'
import { Route as ApiPublicPaymentsWebhookProviderRouteImport } from './routes/api/public/payments.webhook.$provider'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsSlugRoute = TournamentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TournamentsRoute,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamsRoute,
} as any)
const AuthenticatedWithdrawalsRoute =
  AuthenticatedWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisputesRoute = AuthenticatedDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedTeamsCreateRoute =
  AuthenticatedTeamsCreateRouteImport.update({
    id: '/teams/create',
    path: '/teams/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatchesIdRoute = AuthenticatedMatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTournamentsRoute =
  AuthenticatedAdminTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOperationsRoute =
  AuthenticatedAdminOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMatchesRoute =
  AuthenticatedAdminMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDisputesIdRoute =
  AuthenticatedAdminDisputesIdRouteImport.update({
    id: '/disputes/$id',
    path: '/disputes/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicPaymentsWebhookProviderRoute =
  ApiPublicPaymentsWebhookProviderRouteImport.update({
    id: '/api/public/payments/webhook/$provider',
    path: '/api/public/payments/webhook/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disputes': typeof AuthenticatedDisputesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/teams/$id': typeof TeamsIdRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/matches': typeof AuthenticatedAdminMatchesRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/matches/$id': typeof AuthenticatedMatchesIdRoute
  '/teams/create': typeof AuthenticatedTeamsCreateRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/disputes/$id': typeof AuthenticatedAdminDisputesIdRoute
  '/api/public/payments/webhook/$provider': typeof ApiPublicPaymentsWebhookProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disputes': typeof AuthenticatedDisputesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/teams/$id': typeof TeamsIdRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/matches': typeof AuthenticatedAdminMatchesRoute
  '/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/matches/$id': typeof AuthenticatedMatchesIdRoute
  '/teams/create': typeof AuthenticatedTeamsCreateRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/disputes/$id': typeof AuthenticatedAdminDisputesIdRoute
  '/api/public/payments/webhook/$provider': typeof ApiPublicPaymentsWebhookProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disputes': typeof AuthenticatedDisputesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdrawals': typeof AuthenticatedWithdrawalsRoute
  '/teams/$id': typeof TeamsIdRoute
  '/tournaments/$slug': typeof TournamentsSlugRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/matches': typeof AuthenticatedAdminMatchesRoute
  '/_authenticated/admin/operations': typeof AuthenticatedAdminOperationsRoute
  '/_authenticated/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/_authenticated/matches/$id': typeof AuthenticatedMatchesIdRoute
  '/_authenticated/teams/create': typeof AuthenticatedTeamsCreateRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/disputes/$id': typeof AuthenticatedAdminDisputesIdRoute
  '/api/public/payments/webhook/$provider': typeof ApiPublicPaymentsWebhookProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/teams'
    | '/tournaments'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/disputes'
    | '/notifications'
    | '/profile'
    | '/wallet'
    | '/withdrawals'
    | '/teams/$id'
    | '/tournaments/$slug'
    | '/admin/finance'
    | '/admin/matches'
    | '/admin/operations'
    | '/admin/tournaments'
    | '/matches/$id'
    | '/teams/create'
    | '/admin/'
    | '/admin/disputes/$id'
    | '/api/public/payments/webhook/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/leaderboard'
    | '/teams'
    | '/tournaments'
    | '/change-password'
    | '/dashboard'
    | '/disputes'
    | '/notifications'
    | '/profile'
    | '/wallet'
    | '/withdrawals'
    | '/teams/$id'
    | '/tournaments/$slug'
    | '/admin/finance'
    | '/admin/matches'
    | '/admin/operations'
    | '/admin/tournaments'
    | '/matches/$id'
    | '/teams/create'
    | '/admin'
    | '/admin/disputes/$id'
    | '/api/public/payments/webhook/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/leaderboard'
    | '/teams'
    | '/tournaments'
    | '/_authenticated/admin'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/disputes'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/wallet'
    | '/_authenticated/withdrawals'
    | '/teams/$id'
    | '/tournaments/$slug'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/matches'
    | '/_authenticated/admin/operations'
    | '/_authenticated/admin/tournaments'
    | '/_authenticated/matches/$id'
    | '/_authenticated/teams/create'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/disputes/$id'
    | '/api/public/payments/webhook/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TournamentsRoute: typeof TournamentsRouteWithChildren
  ApiPublicPaymentsWebhookProviderRoute: typeof ApiPublicPaymentsWebhookProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$slug': {
      id: '/tournaments/$slug'
      path: '/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof TournamentsSlugRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/_authenticated/withdrawals': {
      id: '/_authenticated/withdrawals'
      path: '/withdrawals'
      fullPath: '/withdrawals'
      preLoaderRoute: typeof AuthenticatedWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disputes': {
      id: '/_authenticated/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthenticatedDisputesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/teams/create': {
      id: '/_authenticated/teams/create'
      path: '/teams/create'
      fullPath: '/teams/create'
      preLoaderRoute: typeof AuthenticatedTeamsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matches/$id': {
      id: '/_authenticated/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof AuthenticatedMatchesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tournaments': {
      id: '/_authenticated/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AuthenticatedAdminTournamentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/operations': {
      id: '/_authenticated/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AuthenticatedAdminOperationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/matches': {
      id: '/_authenticated/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AuthenticatedAdminMatchesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/disputes/$id': {
      id: '/_authenticated/admin/disputes/$id'
      path: '/disputes/$id'
      fullPath: '/admin/disputes/$id'
      preLoaderRoute: typeof AuthenticatedAdminDisputesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/payments/webhook/$provider': {
      id: '/api/public/payments/webhook/$provider'
      path: '/api/public/payments/webhook/$provider'
      fullPath: '/api/public/payments/webhook/$provider'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminMatchesRoute: typeof AuthenticatedAdminMatchesRoute
  AuthenticatedAdminOperationsRoute: typeof AuthenticatedAdminOperationsRoute
  AuthenticatedAdminTournamentsRoute: typeof AuthenticatedAdminTournamentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminDisputesIdRoute: typeof AuthenticatedAdminDisputesIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
    AuthenticatedAdminMatchesRoute: AuthenticatedAdminMatchesRoute,
    AuthenticatedAdminOperationsRoute: AuthenticatedAdminOperationsRoute,
    AuthenticatedAdminTournamentsRoute: AuthenticatedAdminTournamentsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminDisputesIdRoute: AuthenticatedAdminDisputesIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisputesRoute: typeof AuthenticatedDisputesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawalsRoute: typeof AuthenticatedWithdrawalsRoute
  AuthenticatedMatchesIdRoute: typeof AuthenticatedMatchesIdRoute
  AuthenticatedTeamsCreateRoute: typeof AuthenticatedTeamsCreateRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisputesRoute: AuthenticatedDisputesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawalsRoute: AuthenticatedWithdrawalsRoute,
  AuthenticatedMatchesIdRoute: AuthenticatedMatchesIdRoute,
  AuthenticatedTeamsCreateRoute: AuthenticatedTeamsCreateRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface TeamsRouteChildren {
  TeamsIdRoute: typeof TeamsIdRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdRoute: TeamsIdRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface TournamentsRouteChildren {
  TournamentsSlugRoute: typeof TournamentsSlugRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsSlugRoute: TournamentsSlugRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TournamentsRoute: TournamentsRouteWithChildren,
  ApiPublicPaymentsWebhookProviderRoute: ApiPublicPaymentsWebhookProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
